title: Block Diagram Protocol
description: Documentation for the block diagram protocol
theme: just-the-docs

url: https://blockscience.github.io/bdp-lib/

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

math: mathjax

aux_links:
  Block Diagram Protocol Repository: https://github.com/BlockScience/bdp-lib